import type { Lead, LeadAllowedActions } from "@/types/lead";

export const noLeadActions: LeadAllowedActions = {
  can_edit: false,
  can_claim: false,
  can_assign: false,
  can_move_stage: false,
  can_move_backward: false,
  can_move_to_lost: false,
  can_reopen: false,
  can_add_note: false,
  can_archive: false,
  can_restore: false,
  can_convert: false,
};

export function leadFixture(overrides: Partial<Lead> = {}): Lead {
  return {
    id: "01LEAD00000000000000000001",
    tenant_id: "01TENANT00000000000000001",
    name: "Test Lead",
    phone: "0501234567",
    email: "lead@example.test",
    source: "website",
    source_detail: null,
    project_id: null,
    unit_id: null,
    stage: "new",
    assigned_to: null,
    next_follow_up_at: null,
    lost_reason: null,
    lost_reason_detail: null,
    lost_at: null,
    lost_by: null,
    customer_id: null,
    converted_at: null,
    converted_by: null,
    conversion_mode: null,
    archived_at: null,
    archived_by: null,
    archive_reason: null,
    archive_reason_detail: null,
    restored_by: null,
    restored_at: null,
    created_by: 1,
    updated_by: null,
    created_at: "2026-08-01T10:00:00Z",
    updated_at: "2026-08-01T10:00:00Z",
    project: null,
    unit: null,
    customer: null,
    allowed_actions: { ...noLeadActions },
    ...overrides,
  };
}
